name: 构建EasyImage镜像-amd64
on:
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::${GITHUB_REF:10}"
          echo "ReleaseTag=${GITHUB_REF:10}"

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx-amd64
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-amd64
          platforms: |
            linux/amd64
          push: true
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/easyimage:${{ steps.set-version.outputs.version }}
             ${{ secrets.DOCKER_USERNAME }}/easyimage:latest

      - 
        name: Buildx-other
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-other
          platforms: |
            linux/amd64
          push: true
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/easyimage:${{ steps.set-version.outputs.version }}-other
             ${{ secrets.DOCKER_USERNAME }}/easyimage:latest-other