name: 构建EasyImage镜像

on:
    release:
        types: [published]

jobs:
  job1:
    name: Build amd64
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - name: Set Version
        id: set-version
        run: |
          echo "version=${GITHUB_REF:10}" >> $GITHUB_OUTPUT
          echo "ReleaseTag=${GITHUB_REF:10}"

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx-amd64
        uses: docker/build-push-action@v4
        with:
          context: .
          file: amd64.Dockerfile
          platforms: |
            linux/amd64
          push: true
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/easyimage:${{ steps.set-version.outputs.version }}_amd64

  job2:
    name: Build arm64
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - name: Set Version
        id: set-version
        run: |
          echo "version=${GITHUB_REF:10}" >> $GITHUB_OUTPUT
          echo "ReleaseTag=${GITHUB_REF:10}"

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx-arm64
        uses: docker/build-push-action@v4
        with:
          context: .
          file: arm.arm64.Dockerfile
          platforms: |
            linux/arm64/v8
          push: true
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/easyimage:${{ steps.set-version.outputs.version }}_arm64

  job3:
    name: Build arm
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - name: Set Version
        id: set-version
        run: |
          echo "version=${GITHUB_REF:10}" >> $GITHUB_OUTPUT
          echo "ReleaseTag=${GITHUB_REF:10}"

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx-arm
        uses: docker/build-push-action@v4
        with:
          context: .
          file: arm.arm64.Dockerfile
          platforms: |
            linux/arm/v7
          push: true
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/easyimage:${{ steps.set-version.outputs.version }}_arm


  job4:
    needs: [job1, job2, job3]
    name: version tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set Version
        id: set-version
        run: |
          echo "version=${GITHUB_REF:10}" >> $GITHUB_OUTPUT
          echo "ReleaseTag=${GITHUB_REF:10}"
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: create version tag
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKER_USERNAME }}/easyimage:${{ steps.set-version.outputs.version }} \
            ${{ secrets.DOCKER_USERNAME }}/easyimage:${{ steps.set-version.outputs.version }}_amd64 \
            ${{ secrets.DOCKER_USERNAME }}/easyimage:${{ steps.set-version.outputs.version }}_arm64 \
            ${{ secrets.DOCKER_USERNAME }}/easyimage:${{ steps.set-version.outputs.version }}_arm


      - name: create latest-amd64 tag
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKER_USERNAME }}/easyimage:latest_amd64 \
            ${{ secrets.DOCKER_USERNAME }}/easyimage:${{ steps.set-version.outputs.version }}_amd64

      - name: create latest-arm64 tag
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKER_USERNAME }}/easyimage:latest_arm64 \
            ${{ secrets.DOCKER_USERNAME }}/easyimage:${{ steps.set-version.outputs.version }}_arm64

      - name: create latest-arm tag
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKER_USERNAME }}/easyimage:latest_arm \
            ${{ secrets.DOCKER_USERNAME }}/easyimage:${{ steps.set-version.outputs.version }}_arm


      - name: create latest tag
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKER_USERNAME }}/easyimage:latest \
            ${{ secrets.DOCKER_USERNAME }}/easyimage:latest_amd64 \
            ${{ secrets.DOCKER_USERNAME }}/easyimage:latest_arm64 \
            ${{ secrets.DOCKER_USERNAME }}/easyimage:latest_arm

  job5:
    needs: [job1, job2, job3, job4]
    name: 更新DockerHub介绍
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/easyimage
          short-description: Easyimage Image
          readme-filepath: ./README.md
